[package]
name = "voidseek"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.13"
wgpu = "29.0.1"
pollster = "0.4.0"
bytemuck = { version = "1.25.0", features = ["derive"] }

[profile.release]
opt-level = 3         # Maximálna optimalizácia na rýchlosť (predvolené je 3, ale pre istotu).
lto = "fat"           # Link Time Optimization: "fat" je agresívnejšie ako "thin". Umožňuje optimalizáciu naprieč všetkými crate-mi.
codegen-units = 1     # Núti kompilátor spracovať kód v jednom vlákne. Spomalí to kompiláciu, ale vytvorí rýchlejší kód.
panic = "abort"       # Pri panike program okamžite skončí bez "odvíjania" stacku. Zvyšuje rýchlosť a znižuje veľkosť.
strip = true          # Odstráni debug symboly. Dramaticky zmenší veľkosť súboru bez vplyvu na rýchlosť.
rpath = false         # Vypne hľadanie dynamických knižníc v rpath (menšia veľkosť).
debug = false         # Žiadne debug info v release builde.
